{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
  labels:
  {{- include "sftp.labels" . | nindent 4 }}
  name: {{ template "sftp.fullname" . }}
spec:
  accessModes:
  {{ toYaml .Values.persistence.accessModes | indent 4 }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  volumeName: "{{ .Values.persistence.volumeName }}"
  {{- if .Values.persistence.volumeBindingModeName }}
  volumeBindingModeName: "{{ .Values.persistence.volumeBindingModeName }}"
  {{- end }}
  {{- if .Values.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  {{- end -}}
  {{- end -}}
