apiVersion: v2
name: sftp
description: A Helm chart to deploy SFTP
type: application
version: 0.2.2
appVersion: 5.1.5

icon: https://raw.githubusercontent.com/EmberStack/CDN/master/Projects/docker-sftp/openssh.png
keywords:
- sftp
- openssh
- files
- storage
- ftp
home: https://github.com/EmberStack/docker-sftp
sources:
- https://github.com/EmberStack/docker-sftp
maintainers:
- name: winromulus
  email: helm-charts@emberstack.com
